version: '3.8'

services:
  api:
    build: .
    container_name: chess-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'