version: '3.8'

services:
  api:
    build: .
    container_name: chess-backend
    ports:
      - "3000:3000"
    environment:
        - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'